var keyMirror = require('keymirror');

module.exports = {

	BLOG_HEADER: 'Blogs',

	ActionTypes: keyMirror({
		BLOG_ADD: null,
		BLOG_REMOVE: null,
		BLOG_UPDATE: null,
		GET_BLOGS: null,
		GET_BLOG_POSTS: null,
		SET_CURRENT_BLOG: null,
		SET_CURRENT_POST: null,
		GET_CURRENT_BLOG: null,
		GET_CURRENT_POST: null
	}),

	BLOG_TITLE_KEY: 'BLOG_TITLE',
	BLOG_DESC_KEY: 'BLOG_DESCRIPTION',
	BLOG_KEY_KEY: 'BLOG_ID',
	BLOG_PARAM_KEY: 'BLOG_PERMA_LINK',
	BLOG_POST_COUNT_KEY: 'BLOG_POST_COUNT',
	BLOG_CHILDREN_KEY: 'out_Own',
	BLOG_INFO_KEY: 'BLOG_INFORMATION',

	BLOG_POST_TITLE_KEY: 'BLOG_POST_TITLE',
	BLOG_POST_DESC_KEY: 'BLOG_POST_DESCRIPTION',
	BLOG_POST_CONTENT_KEY: 'BLOG_POST_CONTENT',
	BLOG_POST_DATE_KEY: 'CREATE_DTTM',
	BLOG_POST_PARAM_KEY: 'BLOG_POST_PERMA_LINK'

};
